version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gorm.io/gorm
    versions:
    - 1.20.12
    - 1.21.1
    - 1.21.2
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.1
    - 1.8.0
  - dependency-name: gorm.io/driver/postgres
    versions:
    - 1.0.7
    - 1.0.8
  - dependency-name: github.com/h2non/filetype
    versions:
    - 1.1.1
  - dependency-name: github.com/DataManager-Go/libdatamanager
    versions:
    - 1.4.0
