apiVersion: v1
kind: PersistentVolume
metadata:
  name: dmanager-files
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "<your path>"
