apiVersion: v1
kind: PersistentVolume
metadata:
  name: dmanager-data-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "<your path>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dmanager-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
